name: 'Setup Stripe CLI'
description: 'Installs the Stripe CLI'

runs:
  using: 'composite'
  steps:
    - name: Install Stripe CLI
      shell: bash
      run: |
        if ! command -v stripe &> /dev/null; then
          echo "Stripe CLI not found. Installing..."
          # Using apt method from e2e-oauth.yml
          curl -s https://packages.stripe.dev/api/security/keypair/stripe-cli-gpg/public | gpg --dearmor | sudo tee /usr/share/keyrings/stripe.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/stripe.gpg] https://packages.stripe.dev/stripe-cli-debian-local stable main" | sudo tee -a /etc/apt/sources.list.d/stripe.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y stripe # Add -y for non-interactive install
          echo "Stripe CLI installed: $(stripe version)"
        else
          echo "Stripe CLI already installed: $(stripe version)"
        fi
