name: 'Setup Node + NPM Deps'
description: 'Sets up Node.js, caches npm dependencies, and installs them. Assumes checkout happened prior.'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '20.x'

runs:
  using: 'composite'
  steps:
    - name: Disable corepack (npm is default)
      shell: bash
      run: corepack disable

    - name: Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: npm ci
