name: 'Setup Supabase CLI'
description: 'Installs the Supabase CLI'

runs:
  using: 'composite'
  steps:
    - name: Install Supabase CLI
      shell: bash
      run: |
        if ! command -v supabase &> /dev/null; then
          echo "Supabase CLI not found. Installing..."
          # Using specific version from original workflow for consistency
          curl -fsSL https://github.com/supabase/cli/releases/download/v1.150.0/supabase_1.150.0_linux_amd64.deb -o supabase.deb
          sudo dpkg -i supabase.deb
          rm supabase.deb
          echo "Supabase CLI installed: $(supabase --version)"
        else
          echo "Supabase CLI already installed: $(supabase --version)"
        fi
