name: Reusable – Node Checkout & Install
on:
  workflow_call:
    inputs:
      node-version:
        required: false
        default: '20'
        type: string
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Disable corepack (npm is default)
        run: corepack disable

      - name: Setup Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
