name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-test:
    name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        os: [ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Install pnpm via Corepack
      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@8.15.1 --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Prettier + ESLint
      - name: Lint
        run: pnpm lint

      # Type check
      - name: Type check
        run: pnpm type-check

      # Jest unit tests with coverage
      - name: Unit tests
        run: pnpm test -- --coverage --runInBand

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.node-version }}
          path: coverage/

      # Build Next.js app once for Playwright
      - name: Build app
        run: pnpm build

      # Playwright smoke tests
      - name: Run Playwright tests
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: pnpm test:e2e

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.node-version }}
          path: playwright-report/
